### PR TITLE
Create requirements.txt

### LINKED ISSUE #12: Add requirement.txt file for dependencies
Issue - Right now, if anyone clones the project for the first time then they may be missing many dependencies required to run. Python will show errors one by one. 
Solution - Create a requirement.txt file, so that we can install all dependencies at once from it.

### PR DESCRIPTION
**Pull request by kartikjoshi267**
Fixes #12

### CODE REVIEW

**Comment by ay2306** [comment]
I don't know if you have included all the dependencies or not.
But `graphviz` is definitely missing.

**Review by ay2306 — CHANGES_REQUESTED** [review]
Where is graphviz?

**Comment by kartikjoshi267** [comment]
> Where is graphviz?

Ok! Let me check!

**Comment by kartikjoshi267** [comment]
> Where is graphviz?

Please check now

**Review by ay2306 — APPROVED** [review]

**Pull request merged**
